# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hoccunggaia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire'

  # Pods for hoccunggaia

  target 'hoccunggaiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hoccunggaiaUITests' do
    # Pods for testing
  end

end
